### ISSUE TITLE
Serde support?

### ISSUE THREAD

**Issue by Lamby777** [rossmacarthur/emojis#16]
Is there any way you guys could add a feature flag for supporting serde?

**Comment by rossmacarthur** [comment]
Could you explain your use case?

Reason being I need to understand which types you are serializing and deserializing (I presume the `Emoji` struct), I imagine we can just serialize and deserialize as a string.

**Comment by rossmacarthur** [comment]
@Lamby777 Here is a draft PR, let me know what you think https://github.com/rossmacarthur/emojis/pull/17

**Comment by Lamby777** [comment]
> Could you explain your use case?

Asked this because I want to (de)serialize a user's preferred skin tone on a config file for an emoji picker so it'll show that skin tone by default for emojis with a single person.

**Comment by Lamby777** [comment]
Just tested it with `emojis = { git = "https://github.com/rossmacarthur/emojis", branch = "serde", features = ["serde"] }` and it compiles fine. Thanks!

(edit: still testing the emoji part, but skin tones works)

**Comment by Lamby777** [comment]
Alright, so `&'static Emoji` implements the traits, but `Emoji` doesn't. When I serialize an emoji reference, it becomes a string containing the emoji, but when I deserialize it using `toml`, I get this:
```
invalid type: string \"🥲\", expected a borrowed string
```
Oddly enough, it works fine when using `serde_json` instead. Is it just something wrong with my implementation?

**Comment by rossmacarthur** [comment]
Thanks for testing it! I have fixed it to work with TOML.
