### ISSUE TITLE
Lookup emoji only by unicode codepoint, not by shorthand

### ISSUE THREAD

**Issue by johannescpk** [rossmacarthur/emojis#7]
Currently `lookup` will try both, shorthand and unicode codepoint . It'd be helpful if there'd be an additional way to do one or the other.

The workaround to manually lookup by unicode codepoint is `emojis::iter().find(..)`.

**Comment by rossmacarthur** [comment]
Yeah it probably makes more sense to have separate functions. How about

```
get(&str)
```
and
```
get_by_shortcode(&str)
```

**Comment by rossmacarthur** [comment]
Fixed in 712f85db9dae14d079b5f80f355fd51690c72ab2

**Comment by johannescpk** [comment]
Sorry for not coming back to your question and thanks for adding dedicated methods!
