### ISSUE TITLE
`get` with HashMap

### ISSUE THREAD

**Issue by Jasperav** [rossmacarthur/emojis#8]
Thanks for creating this up to date library. I want to use this to check if a `str` is an `Emoji`. I am currently calling the `get` method and check if it returns `Some`.

I noticed there is a loop to determine if the unicode is an emoji. I was wondering if it wouldn't be a lot quicker if there is another static (generated) `HashMap<Unicode, Emoji>` to reach O(1) lookup time. I am not sure how Emoji's are encoded, so I am not sure if this is possible.

https://github.com/rossmacarthur/emojis/blob/c5bf0984abffa717e44797091b36b99c79910053/src/lib.rs#L351

**Comment by rossmacarthur** [comment]
Ideally we could use something like [phf](https://crates.io/crates/phf) to generate a compile time map. I agree this would be much nicer.

**Comment by rossmacarthur** [comment]
Finally got around to this :) 

Implemented in [de06cb5](https://github.com/rossmacarthur/emojis/commit/de06cb566622d93f7a2818d1e18878eff893598f)

**Comment by Jasperav** [comment]
@rossmacarthur Thank you very much!
